# Generated by Django 6.0.5 on 2026-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='major',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CM', 'Communications and Media')], max_length=10, null=True),
        ),
    ]
