# Generated by Django 6.0.7 on 2026-07-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_apilog'),
    ]

    operations = [

        migrations.AlterField(
            model_name='bubbleevent',
            name='name',
            field=models.CharField(choices=[('CLEANING', 'CLEANING & DISINFECTION'), ('MCHS', 'MCHS'), ('ALTAI-NARYN FOOTBALL', 'ALTAI-NARYN FOOTBALL SCHOOL'), ('PE', 'PHYSICAL EDUCATION'), ('SECURITY', 'UCA SECURITY'), ('VOLLEYBALL', 'VOLLEYBALL'), ('BASKETBALL', 'BASKETBALL'), ('CRICKET', 'CRICKET'), ('JUDO GRAPPLING', 'JUDO GRAPPLING'), ('MEP&KITCHEN', 'MEP&KITCHEN'), ('TENNIS', 'TENNIS')], default='CLEANING', max_length=100),
        ),
    ]
