# Generated by Django 6.0.5 on 2026-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='sql_queries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
