# Generated by Django 6.0.5 on 2026-08-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0004_apilog_sql_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='sql_queries',
        ),
        migrations.CreateModel(
            name='APISQLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField()),
                ('params', models.TextField(blank=True, null=True)),
                ('duration_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_log', models.ForeignKey(db_column='api_log_id', on_delete=django.db.models.deletion.CASCADE, related_name='sql_queries', to='camphub.apilog')),
            ],
            options={
                'verbose_name': 'API SQL Log',
                'verbose_name_plural': 'API SQL Logs',
                'db_table': 'api_sql_logs',
                'ordering': ['id'],
            },
        ),
    ]
