# Generated by Django 6.0.5 on 2026-08-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0005_remove_apilog_sql_queries_apisqllog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='room_id',
        ),
        migrations.AlterField(
            model_name='bubbleevent',
            name='name',
            field=models.CharField(choices=[('CLEANING', 'CLEANING & DISINFECTION'), ('MCHS', 'MCHS'), ('ALTAI-NARYN FOOTBALL', 'ALTAI-NARYN FOOTBALL SCHOOL'), ('FOOTBALL', 'FOOTBALL'), ('football', 'football'), ('PE', 'PHYSICAL EDUCATION'), ('SECURITY', 'UCA SECURITY'), ('VOLLEYBALL', 'VOLLEYBALL'), ('BASKETBALL', 'BASKETBALL'), ('CRICKET', 'CRICKET'), ('JUDO GRAPPLING', 'JUDO GRAPPLING'), ('MEP&KITCHEN', 'MEP&KITCHEN'), ('TENNIS', 'TENNIS')], default='CLEANING', max_length=100),
        ),
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.JSONField()),
                ('unispace_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
