# Generated by Django 6.0.7 on 2026-08-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_remove_cohort_room_id_alter_bubbleevent_name'),
        ('camphub', '0005_remove_apilog_sql_queries_apisqllog'),
    ]

    operations = [
    ]
