# Generated by Django 6.0.7 on 2026-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0006_merge_20260813_1123'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='cohort',
                    name='room_id',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE camphub_cohort DROP COLUMN IF EXISTS room_id;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='bubbleevent',
            name='name',
            field=models.CharField(choices=[('CLEANING', 'CLEANING & DISINFECTION'), ('MCHS', 'MCHS'), ('ALTAI-NARYN FOOTBALL', 'ALTAI-NARYN FOOTBALL SCHOOL'), ('FOOTBALL', 'FOOTBALL'), ('football', 'football'), ('PE', 'PHYSICAL EDUCATION'), ('SECURITY', 'UCA SECURITY'), ('VOLLEYBALL', 'VOLLEYBALL'), ('BASKETBALL', 'BASKETBALL'), ('CRICKET', 'CRICKET'), ('JUDO GRAPPLING', 'JUDO GRAPPLING'), ('MEP&KITCHEN', 'MEP&KITCHEN'), ('TENNIS', 'TENNIS'), ('UCA FACULTY', 'UCA FACULTY'), ('VOLLEYBALL FEMALE', 'VOLLEYBALL FEMALE'), ('BADMINTON', 'BADMINTON')], default='CLEANING', max_length=100),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(choices=[('CM', 'CM'), ('CS', 'CS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
