# Generated by Django 6.0.7 on 2026-08-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0007_remove_cohort_room_id_alter_bubbleevent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='linked_event_id',
            field=models.ForeignKey(blank=True, db_column='linked_event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='camphub.classevent'),
        ),
    ]
