# Generated by Django 6.0.5 on 2026-07-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0008_remove_classevent_unique_cohort_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubbleevent',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
