# Generated by Django 6.0.7 on 2026-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0008_classevent_linked_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(choices=[('CM_A', 'CM_B'), ('CS_A', 'CS_B'), ('CM', 'CM'), ('CS', 'CS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year_name',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('SOPH', 'Soph'), ('JUN', 'Jun'), ('SEN', 'Sen')], default='SOF', max_length=50),
        ),
    ]
