# Generated by Django 6.0.5 on 2026-07-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0009_alter_bubbleevent_event_id_alter_cohort_cohort_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVLounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvbooking',
            name='lounge_name',
        ),
        migrations.AddField(
            model_name='tvbooking',
            name='lounge_id',
            field=models.ForeignKey(blank=True, db_column='lounge_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.tvlounge'),
        ),
    ]
