# Generated by Django 6.0.7 on 2026-09-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0009_alter_cohort_cohort_name_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(choices=[('CM_A', 'CM_B'), ('CS_A', 'CS_A'), ('CM', 'CM'), ('CS', 'CS')], max_length=50),
        ),
    ]
