# Generated by Django 6.0.7 on 2026-09-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0010_alter_cohort_cohort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(choices=[('CM_A', 'CM_A'), ('CS_B', 'CS_B'), ('CM', 'CM'), ('CS', 'CS')], max_length=50),
        ),
    ]
