# Generated by Django 6.0.5 on 2026-09-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0006_remove_cohort_room_id_alter_bubbleevent_name_and_more'),
        ('camphub', '0012_alter_cohort_cohort_name'),
    ]

    operations = [
    ]
