# Generated by Django 6.0.5 on 2026-08-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0017_bubbleevent_choices_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubbleevent',
            name='name',
            field=models.CharField(choices=[('CLEANING', 'CLEANING & DISINFECTION'), ('MCHS', 'MCHS'), ('ALTAI-NARYN FOOTBALL', 'ALTAI-NARYN FOOTBALL SCHOOL'), ('FOOTBALL', 'FOOTBALL'), ('football', 'football'), ('PE', 'PHYSICAL EDUCATION'), ('SECURITY', 'UCA SECURITY'), ('VOLLEYBALL', 'VOLLEYBALL'), ('volleyball', 'volleyball'), ('BASKETBALL', 'BASKETBALL'), ('basketball', 'basketball'), ('CRICKET', 'CRICKET'), ('cricket', 'cricket'), ('JUDO', 'JUDO'), ('judo', 'judo'), ('JUDO GRAPPLING', 'JUDO GRAPPLING'), ('MEP&KITCHEN', 'MEP&KITCHEN'), ('TENNIS', 'TENNIS'), ('tennis', 'tennis'), ('TABLE TENNIS', 'TABLE TENNIS'), ('table tennis', 'table tennis'), ('BADMINTON', 'BADMINTON'), ('badminton', 'badminton'), ('FUTSAL', 'FUTSAL'), ('futsal', 'futsal'), ('CHESS', 'CHESS'), ('chess', 'chess')], default='CLEANING', max_length=100),
        ),
    ]
