# Generated by Django 6.0.5 on 2026-08-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0018_alter_bubbleevent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubbleevent',
            name='name',
            field=models.CharField(choices=[('CLEANING', 'CLEANING & DISINFECTION'), ('MCHS', 'MCHS'), ('ALTAI-NARYN FOOTBALL', 'ALTAI-NARYN FOOTBALL SCHOOL'), ('FOOTBALL', 'FOOTBALL'), ('football', 'football'), ('PE', 'PHYSICAL EDUCATION'), ('SECURITY', 'UCA SECURITY'), ('VOLLEYBALL', 'VOLLEYBALL'), ('BASKETBALL', 'BASKETBALL'), ('CRICKET', 'CRICKET'), ('JUDO GRAPPLING', 'JUDO GRAPPLING'), ('MEP&KITCHEN', 'MEP&KITCHEN'), ('TENNIS', 'TENNIS'), ('UCA FACULTY', 'UCA FACULTY'), ('VOLLEYBALL FEMALE', 'VOLLEYBALL FEMALE'), ('BADMINTON', 'BADMINTON')], default='CLEANING', max_length=100),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year_name',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('SOPH', 'Soph'), ('JUN', 'Jun'), ('SEN', 'Sen')], default='SOF', max_length=50),
        ),
    ]
